version: '3'

services:
  backend:
    image: image_api
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: image_ui
    container_name: frontend
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
